// generated by scripts/make-sw.mjs — do not edit
const CACHE = 'photogram-27c5dc9435'
const ASSETS = ["./assets/bricolage-grotesque-C23fTOVi.woff2","./assets/heic2any-Bh6sxivE.js","./assets/index-B9RkZxiJ.css","./assets/index-DOX4q1n9.js","./assets/worker-Dva3-LyR.js","./favicon.svg","./icon-192.png","./icon-512.png","./index.html","./manifest.webmanifest"]

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request)),
  )
})
