// GENERATED by scripts/make-logo.mjs — do not edit by hand.
// The mark is a real layout: the app's own BSP engine composed it.
export default function Logo({ size = 20 }) {
  return (
    <svg
      width={size}
      height={size * 1.25}
      viewBox="0 0 96 120"
      aria-hidden="true"
      dangerouslySetInnerHTML={{ __html: "<defs><linearGradient id=\"lg0\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\"><stop offset=\"0\" stop-color=\"#64d2ff\"/><stop offset=\"1\" stop-color=\"#0a84ff\"/></linearGradient><linearGradient id=\"lg1\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\"><stop offset=\"0\" stop-color=\"#0a84ff\"/><stop offset=\"1\" stop-color=\"#5e5ce6\"/></linearGradient><linearGradient id=\"lg2\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\"><stop offset=\"0\" stop-color=\"#5e5ce6\"/><stop offset=\"1\" stop-color=\"#bf5af2\"/></linearGradient><linearGradient id=\"lg3\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\"><stop offset=\"0\" stop-color=\"#ffd60a\"/><stop offset=\"1\" stop-color=\"#ff9f0a\"/></linearGradient></defs><rect width=\"96\" height=\"120\" rx=\"24\" fill=\"#101016\"/><rect width=\"96\" height=\"120\" rx=\"24\" fill=\"none\" stroke=\"rgba(255,255,255,0.14)\" stroke-width=\"2\"/><rect x=\"10.0\" y=\"10.0\" width=\"76.0\" height=\"35.8\" rx=\"7\" fill=\"url(#lg2)\"/><rect x=\"48.2\" y=\"52.8\" width=\"37.8\" height=\"57.2\" rx=\"7\" fill=\"url(#lg1)\"/><rect x=\"10.0\" y=\"84.9\" width=\"31.2\" height=\"25.1\" rx=\"7\" fill=\"url(#lg3)\"/><rect x=\"10.0\" y=\"52.8\" width=\"31.2\" height=\"25.1\" rx=\"7\" fill=\"url(#lg0)\"/>" }}
    />
  )
}
