// Brand assets, generated: the wordmark is "photogram" set in Unbounded 500
// (lowercase, tracking −1.5%), converted to vector paths so the header and
// the README banner render the exact same lettering with no font loading.
// The mark beside it is composed by the app's own BSP layout engine.
// Run: node scripts/make-brand.mjs   (expects /tmp/unbounded.ttf)
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import opentype from 'opentype.js'
import { computeLayout } from '../src/lib/layout.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

// --- logo mark ---
const MW = 96
const MH = 120
const { rects } = computeLayout([1.6, 0.8, 1.2, 1.0], {
  canvasW: MW,
  canvasH: MH,
  margin: 10,
  gutter: 7,
  baseSeed: 20260817,
})
const gradients = [
  ['#ffffff', '#c3c7cf'],
  ['#dfe2e8', '#9aa0ab'],
  ['#b9bec8', '#787d88'],
  ['#f4f5f7', '#aeb3bd'],
]
const order = rects
  .map((r, i) => ({ i, area: r.w * r.h }))
  .sort((a, b) => a.area - b.area)
  .map((x) => x.i)
const fillIndex = new Array(rects.length)
fillIndex[order[0]] = 3
order.slice(1).forEach((ri, k) => (fillIndex[ri] = k % 3))
const tiles = rects
  .map(
    (r, i) =>
      `<rect x="${r.x.toFixed(1)}" y="${r.y.toFixed(1)}" width="${r.w.toFixed(1)}" height="${r.h.toFixed(1)}" rx="7" fill="url(#g${fillIndex[i]})"/>`,
  )
  .join('')
const markGroup = (scale, x, y) =>
  `<g transform="translate(${x} ${y}) scale(${scale.toFixed(4)})"><rect width="${MW}" height="${MH}" rx="24" fill="#101016"/><rect width="${MW}" height="${MH}" rx="24" fill="none" stroke="rgba(255,255,255,0.14)" stroke-width="2"/>${tiles}</g>`

// --- wordmark paths ---
const ttf = readFileSync('/tmp/unbounded.ttf')
const font = opentype.parse(ttf.buffer.slice(ttf.byteOffset, ttf.byteOffset + ttf.byteLength))
const SIZE = 90
const path = font.getPath('photogram', 0, 0, SIZE, { kerning: true, letterSpacing: -0.015 })
const bb = path.getBoundingBox()
const d = path.toPathData(2)
const wordW = bb.x2 - bb.x1
const wordH = bb.y2 - bb.y1

// --- Wordmark.jsx for the app header (viewBox tight around the word) ---
writeFileSync(
  join(root, 'src/components/Wordmark.jsx'),
  `// GENERATED by scripts/make-brand.mjs — do not edit by hand.
// "photogram" in Unbounded 500, lowercase, tracking −1.5%, as vector paths.
export default function Wordmark({ height = 16 }) {
  const w = ${wordW.toFixed(1)}
  const h = ${wordH.toFixed(1)}
  return (
    <svg
      height={height}
      width={(height * w) / h}
      viewBox="${bb.x1.toFixed(1)} ${bb.y1.toFixed(1)} ${wordW.toFixed(1)} ${wordH.toFixed(1)}"
      role="img"
      aria-label="photogram"
      fill="currentColor"
      dangerouslySetInnerHTML={{ __html: ${JSON.stringify(`<path d="${d}"/>`)} }}
    />
  )
}
`,
)

// --- banner.svg for the README ---
const PAD = 46
const GAP = 42
const markScale = (wordH + 26) / MH
const markW = MW * markScale
const markH = MH * markScale
const W = Math.ceil(PAD * 2 + markW + GAP + wordW)
const H = Math.ceil(PAD * 2 + Math.max(markH, wordH))
const defs =
  gradients
    .map(
      ([a, b], i) =>
        `<linearGradient id="g${i}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient>`,
    )
    .join('') +
  `<linearGradient id="word" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ffffff"/><stop offset="0.38" stop-color="#e9ebef"/><stop offset="0.52" stop-color="#adb2bd"/><stop offset="0.66" stop-color="#d4d7dd"/><stop offset="1" stop-color="#f2f3f6"/></linearGradient><linearGradient id="gloss" x1="0" y1="0" x2="1" y2="0.35"><stop offset="0.42" stop-color="#ffffff" stop-opacity="0"/><stop offset="0.5" stop-color="#ffffff" stop-opacity="0.55"/><stop offset="0.58" stop-color="#ffffff" stop-opacity="0"/></linearGradient>`
const textX = PAD + markW + GAP - bb.x1
const textY = (H - wordH) / 2 - bb.y1
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" width="${W}" height="${H}">
<defs>${defs}</defs>
<rect width="${W}" height="${H}" rx="28" fill="#0a0a0f"/>
${markGroup(markScale, PAD, (H - markH) / 2)}
<path transform="translate(${textX.toFixed(1)} ${textY.toFixed(1)})" d="${d}" fill="url(#word)"/>
<path transform="translate(${textX.toFixed(1)} ${textY.toFixed(1)})" d="${d}" fill="url(#gloss)"/>
</svg>
`
mkdirSync(join(root, 'docs'), { recursive: true })
writeFileSync(join(root, 'docs/brand.svg'), svg)
console.log(`wordmark ${wordW.toFixed(0)}×${wordH.toFixed(0)}, banner ${W}×${H}`)
