// Post-build: write a precaching service worker into dist/. The asset list is
// enumerated from the build output and the cache name is a hash of it, so a
// new deploy swaps caches atomically and an unchanged one is a no-op.
// Cache-first: after the first visit the app runs fully offline — which is
// also its normal posture, photos never touch the network anyway.
import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { dirname, join, relative } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const dist = join(root, 'dist')

const files = []
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name)
    if (statSync(p).isDirectory()) walk(p)
    else if (name !== 'sw.js') files.push('./' + relative(dist, p).replaceAll('\\', '/'))
  }
}
walk(dist)

const hash = createHash('sha1')
for (const f of files.sort()) hash.update(f + ':' + statSync(join(dist, f)).size)
const version = hash.digest('hex').slice(0, 10)

const sw = `// generated by scripts/make-sw.mjs — do not edit
const CACHE = 'photogram-${version}'
const ASSETS = ${JSON.stringify(files.sort(), null, 0)}

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request)),
  )
})
`
writeFileSync(join(dist, 'sw.js'), sw)
console.log(`dist/sw.js written: ${files.length} assets, cache photogram-${version}`)
