// Generates the app logo with the app's own layout engine: a miniature 4:5
// collage composed by the same BSP partition that builds real slides.
// Outputs src/components/Logo.jsx (inline SVG, zero network requests) and
// public/favicon.svg. Run: node scripts/make-logo.mjs
import { writeFileSync, mkdirSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { computeLayout } from '../src/lib/layout.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const W = 96
const H = 120 // 4:5, the product's canvas
const aspects = [1.6, 0.8, 1.2, 1.0]
const { rects } = computeLayout(aspects, { canvasW: W, canvasH: H, margin: 10, gutter: 7, baseSeed: 20260817 })

// glass-era palette: teal → blue → indigo, one warm spark
const gradients = [
  ['#64d2ff', '#0a84ff'],
  ['#0a84ff', '#5e5ce6'],
  ['#5e5ce6', '#bf5af2'],
  ['#ffd60a', '#ff9f0a'],
]

// the smallest rect gets the warm spark; the rest run cool
const order = rects
  .map((r, i) => ({ i, area: r.w * r.h }))
  .sort((a, b) => a.area - b.area)
  .map((x) => x.i)
const fillIndex = new Array(rects.length)
fillIndex[order[0]] = 3
order.slice(1).forEach((ri, k) => (fillIndex[ri] = k % 3))

const defs = gradients
  .map(
    ([a, b], i) =>
      `<linearGradient id="lg${i}" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient>`,
  )
  .join('')

const tiles = rects
  .map(
    (r, i) =>
      `<rect x="${r.x.toFixed(1)}" y="${r.y.toFixed(1)}" width="${r.w.toFixed(1)}" height="${r.h.toFixed(1)}" rx="7" fill="url(#lg${fillIndex[i]})"/>`,
  )
  .join('')

const body = `<defs>${defs}</defs><rect width="${W}" height="${H}" rx="24" fill="#101016"/><rect width="${W}" height="${H}" rx="24" fill="none" stroke="rgba(255,255,255,0.14)" stroke-width="2"/>${tiles}`

writeFileSync(
  join(root, 'src/components/Logo.jsx'),
  `// GENERATED by scripts/make-logo.mjs — do not edit by hand.
// The mark is a real layout: the app's own BSP engine composed it.
export default function Logo({ size = 20 }) {
  return (
    <svg
      width={size}
      height={size * 1.25}
      viewBox="0 0 ${W} ${H}"
      aria-hidden="true"
      dangerouslySetInnerHTML={{ __html: ${JSON.stringify(body)} }}
    />
  )
}
`,
)

mkdirSync(join(root, 'public'), { recursive: true })
writeFileSync(join(root, 'public/favicon.svg'), `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}">${body}</svg>`)
console.log('logo written:', rects.map((r) => `${Math.round(r.w)}×${Math.round(r.h)}`).join(' '))
